baseURL = "https://brandywjw.cn"
languageCode = "zh-cn"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "brandy6.0"
[[menu.main]]
URL = "about"
name = "关于我"
weight = 2
[[menu.main]]
URL = "contact"
name = "联系方式"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "哈尔滨工业大学威海"
author = "Brandy6.0"
author_image = "images/banner-img.png"
bio = "我是王静雯，来自哈尔滨工业大学（威海）的小可爱~"
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by my boyfriend"
description = "This is meta description"
email = "haha"
google_analitycs_id = "Your ID"
home = "主页"
layout = "1"
logo = "images/brandy.jpg"
mobile = "想联系我，请告知我的npy~"
preloader = true
search = true
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = true
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "baidu.com"
icon = "qq"
